// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const firewallNatCollection = "firewall/nat"

var (
	_ resource.Resource                = &firewallNatResource{}
	_ resource.ResourceWithConfigure   = &firewallNatResource{}
	_ resource.ResourceWithImportState = &firewallNatResource{}
)

type firewallNatResource struct{ client *client.Client }

func NewFirewallNatResource() resource.Resource { return &firewallNatResource{} }

type firewallNatModel struct {
	ID       types.String      `tfsdk:"id"`
	Managed  types.Bool        `tfsdk:"managed"`
	ETag     types.String      `tfsdk:"etag"`
	Enabled  types.Bool        `tfsdk:"enabled"`
	Name     types.String      `tfsdk:"name"`
	SnatIp   types.String      `tfsdk:"snat_ip"`
	SnatPort types.String      `tfsdk:"snat_port"`
	Target   types.String      `tfsdk:"target"`
	Match    *firewallNatMatch `tfsdk:"match"`
}

type firewallNatMatch struct {
	SrcZone  types.String `tfsdk:"src_zone"`
	Device   types.String `tfsdk:"device"`
	SrcIP    types.String `tfsdk:"src_ip"`
	SrcPort  types.String `tfsdk:"src_port"`
	DestIP   types.String `tfsdk:"dest_ip"`
	DestPort types.String `tfsdk:"dest_port"`
	Proto    types.List   `tfsdk:"proto"`
	Mark     types.String `tfsdk:"mark"`
	Family   types.String `tfsdk:"family"`
}

func (r *firewallNatResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_nat"
}

func (r *firewallNatResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *firewallNatResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Firewall NAT rule.",
		Attributes: map[string]schema.Attribute{
			"id":        optionalComputedIDAttribute(),
			"managed":   managedAttribute(),
			"etag":      etagAttribute(),
			"enabled":   optionalComputedBool("Whether the entry is active."),
			"name":      optionalComputedString("Human-readable label for this NAT rule."),
			"snat_ip":   optionalComputedString("IPv4 address to rewrite the source to. Requires target SNAT."),
			"snat_port": optionalComputedString("Port or port range to rewrite the source port to. Requires target SNAT."),
			"target":    optionalComputedString("What to do with matched traffic: `SNAT` rewrites the source to `snat_ip`/`snat_port`, `MASQUERADE` rewrites it to the outbound interface address, `ACCEPT` exempts it from source NAT. Defaults to `MASQUERADE`."),
			"match": schema.SingleNestedAttribute{
				Required:    true,
				Description: "Match conditions.",
				Attributes: map[string]schema.Attribute{
					"src_zone":  optionalComputedString("Outbound (postrouting) zone this rule applies to. Unset matches all egress traffic."),
					"device":    optionalComputedString("Outbound interface name to match."),
					"src_ip":    optionalComputedString("Source address to match: an address, a prefix in either family, or a uci network name. Prefix with `!` to negate."),
					"src_port":  optionalComputedString("Source port or range to match. Prefix with `!` to negate."),
					"dest_ip":   optionalComputedString("Destination address to match, in the same forms as `src_ip`."),
					"dest_port": optionalComputedString("Destination port or range to match. Prefix with `!` to negate."),
					"proto":     optionalComputedStringList("Protocols to match, by name or number (`tcp`, `udp`, `gre`, `sctp`, `47`) or a wildcard (`all`, `any`, `tcpudp`). Every protocol must be tcp or udp when a port is matched, because firewall4 keeps a port match only on those. Defaults to all when unset."),
					"mark":      optionalComputedString("Match an fwmark as a value or value/mask, decimal or `0x` hex. Prefix with `!` to negate."),
					"family":    optionalComputedString("Address family: any, ipv4, or ipv6. Unset means IPv4 only, firewall4's backwards-compatible default for NAT; set `any` for dual-stack."),
				},
			},
		},
	}
}

func (r *firewallNatResource) body(ctx context.Context, m firewallNatModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	if create {
		putStr(out, "id", m.ID)
	}
	putBool(out, "enabled", m.Enabled)
	putStr(out, "name", m.Name)
	putStr(out, "snat_ip", m.SnatIp)
	putStr(out, "snat_port", m.SnatPort)
	putStr(out, "target", m.Target)
	match := map[string]any{}
	if m.Match != nil {
		putStr(match, "src_zone", m.Match.SrcZone)
		putStr(match, "device", m.Match.Device)
		putStr(match, "src_ip", m.Match.SrcIP)
		putStr(match, "src_port", m.Match.SrcPort)
		putStr(match, "dest_ip", m.Match.DestIP)
		putStr(match, "dest_port", m.Match.DestPort)
		putList(ctx, match, "proto", m.Match.Proto, diags.d)
		putStr(match, "mark", m.Match.Mark)
		putStr(match, "family", m.Match.Family)
	}
	out["match"] = match
	return out
}

func (r *firewallNatResource) read(ctx context.Context, obj map[string]any, m *firewallNatModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Enabled = boolVal(obj, "enabled")
	m.Name = strVal(obj, "name")
	m.SnatIp = strVal(obj, "snat_ip")
	m.SnatPort = strVal(obj, "snat_port")
	m.Target = strVal(obj, "target")
	nested, _ := obj["match"].(map[string]any)
	if nested == nil {
		nested = map[string]any{}
	}
	nm := &firewallNatMatch{}
	nm.SrcZone = strVal(nested, "src_zone")
	nm.Device = strVal(nested, "device")
	nm.SrcIP = strVal(nested, "src_ip")
	nm.SrcPort = strVal(nested, "src_port")
	nm.DestIP = strVal(nested, "dest_ip")
	nm.DestPort = strVal(nested, "dest_port")
	nm.Proto = diags.list(listVal(ctx, nested, "proto"))
	nm.Mark = strVal(nested, "mark")
	nm.Family = strVal(nested, "family")
	m.Match = nm
}

func (r *firewallNatResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan firewallNatModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+firewallNatCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "firewall NAT rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallNatResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state firewallNatModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+firewallNatCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall NAT rule", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *firewallNatResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state firewallNatModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+firewallNatCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "firewall NAT rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallNatResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state firewallNatModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+firewallNatCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "firewall NAT rule", err)
	}
}

func (r *firewallNatResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, firewallNatCollection, "firewall NAT rule", req, resp)
}
