// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &firewallNatDataSource{}
	_ datasource.DataSourceWithConfigure = &firewallNatDataSource{}
)

type firewallNatDataSource struct{ client *client.Client }

func NewFirewallNatDataSource() datasource.DataSource { return &firewallNatDataSource{} }

func (d *firewallNatDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_nat"
}

func (d *firewallNatDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *firewallNatDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the firewall NAT rule.",
		Attributes: map[string]dsschema.Attribute{
			"id":        dsIDAttribute(),
			"managed":   dsManagedAttribute(),
			"etag":      dsComputedString("Opaque ETag of the resource's current state."),
			"enabled":   dsComputedBool("Whether the entry is active."),
			"name":      dsComputedString("Human-readable label for this NAT rule."),
			"snat_ip":   dsComputedString("IPv4 address to rewrite the source to. Requires target SNAT."),
			"snat_port": dsComputedString("Port or port range to rewrite the source port to. Requires target SNAT."),
			"target":    dsComputedString("What to do with matched traffic: `SNAT` rewrites the source to `snat_ip`/`snat_port`, `MASQUERADE` rewrites it to the outbound interface address, `ACCEPT` exempts it from source NAT. Defaults to `MASQUERADE`."),
			"match": dsschema.SingleNestedAttribute{
				Computed:    true,
				Description: "Match conditions.",
				Attributes: map[string]dsschema.Attribute{
					"src_zone":  dsComputedString("Outbound (postrouting) zone this rule applies to. Unset matches all egress traffic."),
					"device":    dsComputedString("Outbound interface name to match."),
					"src_ip":    dsComputedString("Source address to match: an address, a prefix in either family, or a uci network name. Prefix with `!` to negate."),
					"src_port":  dsComputedString("Source port or range to match. Prefix with `!` to negate."),
					"dest_ip":   dsComputedString("Destination address to match, in the same forms as `src_ip`."),
					"dest_port": dsComputedString("Destination port or range to match. Prefix with `!` to negate."),
					"proto":     dsComputedStringList("Protocols to match, by name or number (`tcp`, `udp`, `gre`, `sctp`, `47`) or a wildcard (`all`, `any`, `tcpudp`). Every protocol must be tcp or udp when a port is matched, because firewall4 keeps a port match only on those. Defaults to all when unset."),
					"mark":      dsComputedString("Match an fwmark as a value or value/mask, decimal or `0x` hex. Prefix with `!` to negate."),
					"family":    dsComputedString("Address family: any, ipv4, or ipv6. Unset means IPv4 only, firewall4's backwards-compatible default for NAT; set `any` for dual-stack."),
				},
			},
		},
	}
}

func (d *firewallNatDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m firewallNatModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+firewallNatCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall NAT rule", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("firewall NAT rule not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&firewallNatResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
