// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

var (
	_ datasource.DataSource              = &firewallRedirectDataSource{}
	_ datasource.DataSourceWithConfigure = &firewallRedirectDataSource{}
)

type firewallRedirectDataSource struct{ client *client.Client }

func NewFirewallRedirectDataSource() datasource.DataSource { return &firewallRedirectDataSource{} }

func (d *firewallRedirectDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_redirect"
}

func (d *firewallRedirectDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *firewallRedirectDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Look up the firewall redirect.",
		Attributes: map[string]dsschema.Attribute{
			"id":              dsIDAttribute(),
			"managed":         dsManagedAttribute(),
			"etag":            dsComputedString("Opaque ETag of the resource's current state."),
			"enabled":         dsComputedBool("Whether the entry is active."),
			"name":            dsComputedString("Optional section name."),
			"reflection":      dsComputedBool("uci option reflection."),
			"reflection_src":  dsComputedString("uci option reflection_src."),
			"reflection_zone": dsComputedStringList("uci option reflection_zone."),
			"target":          dsComputedString("Target / action."),
			"match": dsschema.SingleNestedAttribute{
				Computed:    true,
				Description: "Match conditions.",
				Attributes: map[string]dsschema.Attribute{
					"src_zone":  dsComputedString("Source firewall zone name."),
					"dest_zone": dsComputedString("Destination firewall zone name."),
					"src_ip":    dsComputedStringList("Source IP addresses or CIDRs."),
					"src_port":  dsComputedStringList("Source ports."),
					"src_dport": dsComputedStringList("With target DNAT, the incoming (destination) port or range to redirect. With target SNAT, the source port to rewrite to. One value only."),
					"src_dip":   dsComputedStringList("With target DNAT, the external destination address to match, which also selects the address used for NAT reflection. With target SNAT, the address to rewrite the source to, and required. One value only."),
					"dest_ip":   dsComputedStringList("Internal destination address to rewrite to. One value only."),
					"dest_port": dsComputedStringList("Internal destination port or range to rewrite to. One value only."),
					"proto":     dsComputedStringList("Protocols to match, by name or number (`tcp`, `udp`, `gre`, `sctp`, `47`) or a wildcard (`all`, `any`, `tcpudp`). Every protocol must be tcp or udp when a port is matched, because firewall4 keeps a port match only on those."),
					"family":    dsComputedString("Address family: any, ipv4, or ipv6."),
					"mark":      dsComputedString("Match an fwmark as a value or value/mask, decimal or `0x` hex. Prefix with `!` to negate."),
				},
			},
		},
	}
}

func (d *firewallRedirectDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var m firewallRedirectModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := d.client.GetObject(ctx, "/"+firewallRedirectCollection+"/"+m.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall redirect", err.Error())
		return
	}
	if !found {
		resp.Diagnostics.AddError("firewall redirect not found", "not found")
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	(&firewallRedirectResource{}).read(ctx, obj, &m, ds)
	m.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}
