// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const firewallRuleCollection = "firewall/rules"

var (
	_ resource.Resource                = &firewallRuleResource{}
	_ resource.ResourceWithConfigure   = &firewallRuleResource{}
	_ resource.ResourceWithImportState = &firewallRuleResource{}
)

type firewallRuleResource struct{ client *client.Client }

func NewFirewallRuleResource() resource.Resource { return &firewallRuleResource{} }

type firewallRuleModel struct {
	ID       types.String       `tfsdk:"id"`
	Managed  types.Bool         `tfsdk:"managed"`
	ETag     types.String       `tfsdk:"etag"`
	Enabled  types.Bool         `tfsdk:"enabled"`
	Name     types.String       `tfsdk:"name"`
	SetDscp  types.String       `tfsdk:"set_dscp"`
	SetMark  types.String       `tfsdk:"set_mark"`
	SetXmark types.String       `tfsdk:"set_xmark"`
	Target   types.String       `tfsdk:"target"`
	Match    *firewallRuleMatch `tfsdk:"match"`
}

type firewallRuleMatch struct {
	SrcZone  types.String `tfsdk:"src_zone"`
	DestZone types.String `tfsdk:"dest_zone"`
	SrcIP    types.List   `tfsdk:"src_ip"`
	SrcPort  types.List   `tfsdk:"src_port"`
	DestIP   types.List   `tfsdk:"dest_ip"`
	DestPort types.List   `tfsdk:"dest_port"`
	Proto    types.List   `tfsdk:"proto"`
	Family   types.String `tfsdk:"family"`
	Mark     types.String `tfsdk:"mark"`
	Dscp     types.String `tfsdk:"dscp"`
}

func (r *firewallRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_rule"
}

func (r *firewallRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *firewallRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Firewall rule.",
		Attributes: map[string]schema.Attribute{
			"id":        optionalComputedIDAttribute(),
			"managed":   managedAttribute(),
			"etag":      etagAttribute(),
			"enabled":   optionalComputedBool("Whether the entry is active."),
			"name":      optionalComputedString("Optional section name."),
			"set_dscp":  optionalComputedString("DSCP class (`CS0` to `CS7`, `BE`, `LE`, `AF11` to `AF43`, `EF`, case-insensitive) or value 0-63 to set. Required by target DSCP."),
			"set_mark":  optionalComputedString("fwmark to set, as a value or value/mask (decimal or `0x` hex). Target MARK requires this or `set_xmark`."),
			"set_xmark": optionalComputedString("fwmark to set with XOR semantics, as a value or value/mask. The alternative to `set_mark` for target MARK."),
			"target":    schema.StringAttribute{Required: true, Description: "Target / action."},
			"match": schema.SingleNestedAttribute{
				Required:    true,
				Description: "Match conditions.",
				Attributes: map[string]schema.Attribute{
					"src_zone":  optionalComputedString("Source firewall zone name. Omit it for an output-chain rule; target NOTRACK requires a real zone name here (not the `*` wildcard)."),
					"dest_zone": optionalComputedString("Destination firewall zone name."),
					"src_ip":    optionalComputedStringList("Source IP addresses or CIDRs."),
					"src_port":  optionalComputedStringList("Source ports."),
					"dest_ip":   optionalComputedStringList("Destination IP addresses or CIDRs."),
					"dest_port": optionalComputedStringList("Destination ports."),
					"proto":     optionalComputedStringList("Protocols to match, by name or number (`tcp`, `udp`, `gre`, `sctp`, `47`) or a wildcard (`all`, `any`, `tcpudp`). Every protocol must be tcp or udp when a port is matched, because firewall4 keeps a port match only on those."),
					"family":    optionalComputedString("Address family: any, ipv4, or ipv6."),
					"mark":      optionalComputedString("Match an fwmark as a value or value/mask, decimal or `0x` hex. Prefix with `!` to negate."),
					"dscp":      optionalComputedString("Match a DSCP class (`CS0` to `CS7`, `BE`, `LE`, `AF11` to `AF43`, `EF`, case-insensitive) or a value 0-63. Prefix with `!` to negate."),
				},
			},
		},
	}
}

func (r *firewallRuleResource) body(ctx context.Context, m firewallRuleModel, diags *diagsink, create bool) map[string]any {
	out := map[string]any{}
	if create {
		putStr(out, "id", m.ID)
	}
	putBool(out, "enabled", m.Enabled)
	putStr(out, "name", m.Name)
	putStr(out, "set_dscp", m.SetDscp)
	putStr(out, "set_mark", m.SetMark)
	putStr(out, "set_xmark", m.SetXmark)
	putStr(out, "target", m.Target)
	match := map[string]any{}
	if m.Match != nil {
		putStr(match, "src_zone", m.Match.SrcZone)
		putStr(match, "dest_zone", m.Match.DestZone)
		putList(ctx, match, "src_ip", m.Match.SrcIP, diags.d)
		putList(ctx, match, "src_port", m.Match.SrcPort, diags.d)
		putList(ctx, match, "dest_ip", m.Match.DestIP, diags.d)
		putList(ctx, match, "dest_port", m.Match.DestPort, diags.d)
		putList(ctx, match, "proto", m.Match.Proto, diags.d)
		putStr(match, "family", m.Match.Family)
		putStr(match, "mark", m.Match.Mark)
		putStr(match, "dscp", m.Match.Dscp)
	}
	out["match"] = match
	return out
}

func (r *firewallRuleResource) read(ctx context.Context, obj map[string]any, m *firewallRuleModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.Enabled = boolVal(obj, "enabled")
	m.Name = strVal(obj, "name")
	m.SetDscp = strVal(obj, "set_dscp")
	m.SetMark = strVal(obj, "set_mark")
	m.SetXmark = strVal(obj, "set_xmark")
	m.Target = strVal(obj, "target")
	nested, _ := obj["match"].(map[string]any)
	if nested == nil {
		nested = map[string]any{}
	}
	nm := &firewallRuleMatch{}
	nm.SrcZone = strVal(nested, "src_zone")
	nm.DestZone = strVal(nested, "dest_zone")
	nm.SrcIP = diags.list(listVal(ctx, nested, "src_ip"))
	nm.SrcPort = diags.list(listVal(ctx, nested, "src_port"))
	nm.DestIP = diags.list(listVal(ctx, nested, "dest_ip"))
	nm.DestPort = diags.list(listVal(ctx, nested, "dest_port"))
	nm.Proto = diags.list(listVal(ctx, nested, "proto"))
	nm.Family = strVal(nested, "family")
	nm.Mark = strVal(nested, "mark")
	nm.Dscp = strVal(nested, "dscp")
	m.Match = nm
}

func (r *firewallRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan firewallRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, true)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Post(ctx, "/"+firewallRuleCollection, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "creating", "firewall rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state firewallRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, "/"+firewallRuleCollection+"/"+state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading firewall rule", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *firewallRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state firewallRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	body := r.body(ctx, plan, ds, false)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Put(ctx, "/"+firewallRuleCollection+"/"+plan.ID.ValueString(), body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "firewall rule", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *firewallRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state firewallRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.Delete(ctx, "/"+firewallRuleCollection+"/"+state.ID.ValueString(), state.ETag.ValueString()); err != nil {
		writeErr(&resp.Diagnostics, "deleting", "firewall rule", err)
	}
}

func (r *firewallRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByID(ctx, r.client, firewallRuleCollection, "firewall rule", req, resp)
}
