// Code generated by internal/gen. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/openwrt-iac/terraform-provider-uapi/internal/client"
)

const prometheusNodeExporterLuaConfigPath = "/prometheus_node_exporter_lua/config"

var (
	_ resource.Resource                = &prometheusNodeExporterLuaConfigResource{}
	_ resource.ResourceWithConfigure   = &prometheusNodeExporterLuaConfigResource{}
	_ resource.ResourceWithImportState = &prometheusNodeExporterLuaConfigResource{}
)

type prometheusNodeExporterLuaConfigResource struct{ client *client.Client }

func NewPrometheusNodeExporterLuaConfigResource() resource.Resource {
	return &prometheusNodeExporterLuaConfigResource{}
}

type prometheusNodeExporterLuaConfigModel struct {
	ID              types.String `tfsdk:"id"`
	Managed         types.Bool   `tfsdk:"managed"`
	ETag            types.String `tfsdk:"etag"`
	ListenInterface types.String `tfsdk:"listen_interface"`
	ListenPort      types.Int64  `tfsdk:"listen_port"`
}

func (r *prometheusNodeExporterLuaConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_prometheus_node_exporter_lua_config"
}

func (r *prometheusNodeExporterLuaConfigResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *prometheusNodeExporterLuaConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Prometheus node_exporter config.",
		Attributes: map[string]schema.Attribute{
			"id":               computedIDAttribute(),
			"managed":          managedAttribute(),
			"etag":             etagAttribute(),
			"listen_interface": optionalComputedString("uci option listen_interface."),
			"listen_port":      optionalComputedInt64("uci option listen_port."),
		},
	}
}

func (r *prometheusNodeExporterLuaConfigResource) body(ctx context.Context, m prometheusNodeExporterLuaConfigModel, diags *diagsink) map[string]any {
	out := map[string]any{}
	putStr(out, "listen_interface", m.ListenInterface)
	putInt64(out, "listen_port", m.ListenPort)
	return out
}

func (r *prometheusNodeExporterLuaConfigResource) read(ctx context.Context, obj map[string]any, m *prometheusNodeExporterLuaConfigModel, diags *diagsink) {
	m.ID = strVal(obj, "id")
	m.Managed = boolVal(obj, "managed")
	m.ListenInterface = strVal(obj, "listen_interface")
	m.ListenPort = int64Val(obj, "listen_port")
}

func (r *prometheusNodeExporterLuaConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan prometheusNodeExporterLuaConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	ctx = client.WithWarner(ctx, ds)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, prometheusNodeExporterLuaConfigPath, body, "")
	if err != nil {
		writeErr(&resp.Diagnostics, "configuring", "prometheus node_exporter config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *prometheusNodeExporterLuaConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state prometheusNodeExporterLuaConfigModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, found, err := r.client.GetObject(ctx, prometheusNodeExporterLuaConfigPath)
	if err != nil {
		resp.Diagnostics.AddError("Error reading prometheus node_exporter config", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	r.read(ctx, obj, &state, ds)
	state.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *prometheusNodeExporterLuaConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state prometheusNodeExporterLuaConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ds := newDiagsink(&resp.Diagnostics)
	ctx = client.WithWarner(ctx, ds)
	body := r.body(ctx, plan, ds)
	if resp.Diagnostics.HasError() {
		return
	}
	obj, etag, err := r.client.Patch(ctx, prometheusNodeExporterLuaConfigPath, body, state.ETag.ValueString())
	if err != nil {
		writeErr(&resp.Diagnostics, "updating", "prometheus node_exporter config", err)
		return
	}
	r.read(ctx, obj, &plan, ds)
	plan.ETag = types.StringValue(etag)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete is a no-op: a singleton cannot be removed; state is just dropped.
func (r *prometheusNodeExporterLuaConfigResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}

func (r *prometheusNodeExporterLuaConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
